name: __APPLICATION_NAME__
load: lib/application.rb
identifier: com.yourcompany.__APPLICATION_NAME__
version: "1.0"
icon: resources/HotCocoa.icns
resources:
  - resources/**/*.*
sources: 
  - lib/**/*.rb
